;addr_internal_inc_ms: 	equ 09h
;addr_inc_ms: 			equ 10h
;addr_inc_s: 			equ 11h
;addr_inc_m: 			equ 12h
;addr_inc_h: 			equ 13h
;
;read_addr_inc_ms: 		equ 04h
;read_addr_inc_s: 		equ 05h
;read_addr_inc_m: 		equ 06h
;read_addr_inc_h: 		equ 07h
;
;addr_lng_p: 			equ 14h
;addr_shrt_p: 			equ 15h
;
;addr_acc_mode: 		equ 16h
;sec_mode: 				equ 01h
;halfsec_mode: 			equ 02h
;tenthsec_mode: 		equ 03h
;
;md_flg: 				equ 50h
;
;count_saved:			equ 30h
;read_saved: 			equ 31h
;save_time_index:		equ 40h
;
;ADC_value_0:			equ 50h
;ADC_value_1:			equ 51h
;ADC_value_2:			equ 52h
;ADC_value_3:			equ 53h
;	

;export addr_internal_inc_ms
;export addr_inc_ms
;export addr_inc_s
;export addr_inc_m
;export addr_inc_h
;
;export read_addr_inc_ms
;export read_addr_inc_s
;export read_addr_inc_m
;export read_addr_inc_h
;
;export addr_lng_p
;export addr_shrt_p
;
;export addr_acc_mode
;;export sec_mode
;;export halfsec_mode
;;export tenthsec_mode
;
;export md_flg
;
;export count_saved
;export read_saved
;export save_time_index
;
;export ADC_value_0
;export ADC_value_1
;export ADC_value_2
;export ADC_value_3
	



sec_mode: 				equ 01h
halfsec_mode: 			equ 02h
tenthsec_mode: 			equ 03h