/******************************************************************************
*  Generated by PSoC Designer 5.4.2946
******************************************************************************/
#include <m8c.h>
// nc address and mask defines
#pragma	ioport	nc_Data_ADDR:	0x0
BYTE			nc_Data_ADDR;
#pragma	ioport	nc_DriveMode_0_ADDR:	0x100
BYTE			nc_DriveMode_0_ADDR;
#pragma	ioport	nc_DriveMode_1_ADDR:	0x101
BYTE			nc_DriveMode_1_ADDR;
#pragma	ioport	nc_DriveMode_2_ADDR:	0x3
BYTE			nc_DriveMode_2_ADDR;
#pragma	ioport	nc_GlobalSelect_ADDR:	0x2
BYTE			nc_GlobalSelect_ADDR;
#pragma	ioport	nc_IntCtrl_0_ADDR:	0x102
BYTE			nc_IntCtrl_0_ADDR;
#pragma	ioport	nc_IntCtrl_1_ADDR:	0x103
BYTE			nc_IntCtrl_1_ADDR;
#pragma	ioport	nc_IntEn_ADDR:	0x1
BYTE			nc_IntEn_ADDR;
#define nc_MASK 0x1
// Test_SignalOutput address and mask defines
#pragma	ioport	Test_SignalOutput_Data_ADDR:	0x0
BYTE			Test_SignalOutput_Data_ADDR;
#pragma	ioport	Test_SignalOutput_DriveMode_0_ADDR:	0x100
BYTE			Test_SignalOutput_DriveMode_0_ADDR;
#pragma	ioport	Test_SignalOutput_DriveMode_1_ADDR:	0x101
BYTE			Test_SignalOutput_DriveMode_1_ADDR;
#pragma	ioport	Test_SignalOutput_DriveMode_2_ADDR:	0x3
BYTE			Test_SignalOutput_DriveMode_2_ADDR;
#pragma	ioport	Test_SignalOutput_GlobalSelect_ADDR:	0x2
BYTE			Test_SignalOutput_GlobalSelect_ADDR;
#pragma	ioport	Test_SignalOutput_IntCtrl_0_ADDR:	0x102
BYTE			Test_SignalOutput_IntCtrl_0_ADDR;
#pragma	ioport	Test_SignalOutput_IntCtrl_1_ADDR:	0x103
BYTE			Test_SignalOutput_IntCtrl_1_ADDR;
#pragma	ioport	Test_SignalOutput_IntEn_ADDR:	0x1
BYTE			Test_SignalOutput_IntEn_ADDR;
#define Test_SignalOutput_MASK 0x20
// SignalInput address and mask defines
#pragma	ioport	SignalInput_Data_ADDR:	0x0
BYTE			SignalInput_Data_ADDR;
#pragma	ioport	SignalInput_DriveMode_0_ADDR:	0x100
BYTE			SignalInput_DriveMode_0_ADDR;
#pragma	ioport	SignalInput_DriveMode_1_ADDR:	0x101
BYTE			SignalInput_DriveMode_1_ADDR;
#pragma	ioport	SignalInput_DriveMode_2_ADDR:	0x3
BYTE			SignalInput_DriveMode_2_ADDR;
#pragma	ioport	SignalInput_GlobalSelect_ADDR:	0x2
BYTE			SignalInput_GlobalSelect_ADDR;
#pragma	ioport	SignalInput_IntCtrl_0_ADDR:	0x102
BYTE			SignalInput_IntCtrl_0_ADDR;
#pragma	ioport	SignalInput_IntCtrl_1_ADDR:	0x103
BYTE			SignalInput_IntCtrl_1_ADDR;
#pragma	ioport	SignalInput_IntEn_ADDR:	0x1
BYTE			SignalInput_IntEn_ADDR;
#define SignalInput_MASK 0x80
// XTALout address and mask defines
#pragma	ioport	XTALout_Data_ADDR:	0x4
BYTE			XTALout_Data_ADDR;
#pragma	ioport	XTALout_DriveMode_0_ADDR:	0x104
BYTE			XTALout_DriveMode_0_ADDR;
#pragma	ioport	XTALout_DriveMode_1_ADDR:	0x105
BYTE			XTALout_DriveMode_1_ADDR;
#pragma	ioport	XTALout_DriveMode_2_ADDR:	0x7
BYTE			XTALout_DriveMode_2_ADDR;
#pragma	ioport	XTALout_GlobalSelect_ADDR:	0x6
BYTE			XTALout_GlobalSelect_ADDR;
#pragma	ioport	XTALout_IntCtrl_0_ADDR:	0x106
BYTE			XTALout_IntCtrl_0_ADDR;
#pragma	ioport	XTALout_IntCtrl_1_ADDR:	0x107
BYTE			XTALout_IntCtrl_1_ADDR;
#pragma	ioport	XTALout_IntEn_ADDR:	0x5
BYTE			XTALout_IntEn_ADDR;
#define XTALout_MASK 0x1
// XTALin address and mask defines
#pragma	ioport	XTALin_Data_ADDR:	0x4
BYTE			XTALin_Data_ADDR;
#pragma	ioport	XTALin_DriveMode_0_ADDR:	0x104
BYTE			XTALin_DriveMode_0_ADDR;
#pragma	ioport	XTALin_DriveMode_1_ADDR:	0x105
BYTE			XTALin_DriveMode_1_ADDR;
#pragma	ioport	XTALin_DriveMode_2_ADDR:	0x7
BYTE			XTALin_DriveMode_2_ADDR;
#pragma	ioport	XTALin_GlobalSelect_ADDR:	0x6
BYTE			XTALin_GlobalSelect_ADDR;
#pragma	ioport	XTALin_IntCtrl_0_ADDR:	0x106
BYTE			XTALin_IntCtrl_0_ADDR;
#pragma	ioport	XTALin_IntCtrl_1_ADDR:	0x107
BYTE			XTALin_IntCtrl_1_ADDR;
#pragma	ioport	XTALin_IntEn_ADDR:	0x5
BYTE			XTALin_IntEn_ADDR;
#define XTALin_MASK 0x2
// LEDOut address and mask defines
#pragma	ioport	LEDOut_Data_ADDR:	0x4
BYTE			LEDOut_Data_ADDR;
#pragma	ioport	LEDOut_DriveMode_0_ADDR:	0x104
BYTE			LEDOut_DriveMode_0_ADDR;
#pragma	ioport	LEDOut_DriveMode_1_ADDR:	0x105
BYTE			LEDOut_DriveMode_1_ADDR;
#pragma	ioport	LEDOut_DriveMode_2_ADDR:	0x7
BYTE			LEDOut_DriveMode_2_ADDR;
#pragma	ioport	LEDOut_GlobalSelect_ADDR:	0x6
BYTE			LEDOut_GlobalSelect_ADDR;
#pragma	ioport	LEDOut_IntCtrl_0_ADDR:	0x106
BYTE			LEDOut_IntCtrl_0_ADDR;
#pragma	ioport	LEDOut_IntCtrl_1_ADDR:	0x107
BYTE			LEDOut_IntCtrl_1_ADDR;
#pragma	ioport	LEDOut_IntEn_ADDR:	0x5
BYTE			LEDOut_IntEn_ADDR;
#define LEDOut_MASK 0x80
// LCDD4 address and mask defines
#pragma	ioport	LCDD4_Data_ADDR:	0x8
BYTE			LCDD4_Data_ADDR;
#pragma	ioport	LCDD4_DriveMode_0_ADDR:	0x108
BYTE			LCDD4_DriveMode_0_ADDR;
#pragma	ioport	LCDD4_DriveMode_1_ADDR:	0x109
BYTE			LCDD4_DriveMode_1_ADDR;
#pragma	ioport	LCDD4_DriveMode_2_ADDR:	0xb
BYTE			LCDD4_DriveMode_2_ADDR;
#pragma	ioport	LCDD4_GlobalSelect_ADDR:	0xa
BYTE			LCDD4_GlobalSelect_ADDR;
#pragma	ioport	LCDD4_IntCtrl_0_ADDR:	0x10a
BYTE			LCDD4_IntCtrl_0_ADDR;
#pragma	ioport	LCDD4_IntCtrl_1_ADDR:	0x10b
BYTE			LCDD4_IntCtrl_1_ADDR;
#pragma	ioport	LCDD4_IntEn_ADDR:	0x9
BYTE			LCDD4_IntEn_ADDR;
#define LCDD4_MASK 0x1
// LCDD4 Shadow defines
//   LCDD4_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define LCDD4_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
//   LCDD4_DriveMode_0Shadow define
extern BYTE Port_2_DriveMode_0_SHADE;
#define LCDD4_DriveMode_0Shadow (*(unsigned char*)&Port_2_DriveMode_0_SHADE)
//   LCDD4_DriveMode_1Shadow define
extern BYTE Port_2_DriveMode_1_SHADE;
#define LCDD4_DriveMode_1Shadow (*(unsigned char*)&Port_2_DriveMode_1_SHADE)
// LCDD5 address and mask defines
#pragma	ioport	LCDD5_Data_ADDR:	0x8
BYTE			LCDD5_Data_ADDR;
#pragma	ioport	LCDD5_DriveMode_0_ADDR:	0x108
BYTE			LCDD5_DriveMode_0_ADDR;
#pragma	ioport	LCDD5_DriveMode_1_ADDR:	0x109
BYTE			LCDD5_DriveMode_1_ADDR;
#pragma	ioport	LCDD5_DriveMode_2_ADDR:	0xb
BYTE			LCDD5_DriveMode_2_ADDR;
#pragma	ioport	LCDD5_GlobalSelect_ADDR:	0xa
BYTE			LCDD5_GlobalSelect_ADDR;
#pragma	ioport	LCDD5_IntCtrl_0_ADDR:	0x10a
BYTE			LCDD5_IntCtrl_0_ADDR;
#pragma	ioport	LCDD5_IntCtrl_1_ADDR:	0x10b
BYTE			LCDD5_IntCtrl_1_ADDR;
#pragma	ioport	LCDD5_IntEn_ADDR:	0x9
BYTE			LCDD5_IntEn_ADDR;
#define LCDD5_MASK 0x2
// LCDD5 Shadow defines
//   LCDD5_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define LCDD5_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
//   LCDD5_DriveMode_0Shadow define
extern BYTE Port_2_DriveMode_0_SHADE;
#define LCDD5_DriveMode_0Shadow (*(unsigned char*)&Port_2_DriveMode_0_SHADE)
//   LCDD5_DriveMode_1Shadow define
extern BYTE Port_2_DriveMode_1_SHADE;
#define LCDD5_DriveMode_1Shadow (*(unsigned char*)&Port_2_DriveMode_1_SHADE)
// LCDD6 address and mask defines
#pragma	ioport	LCDD6_Data_ADDR:	0x8
BYTE			LCDD6_Data_ADDR;
#pragma	ioport	LCDD6_DriveMode_0_ADDR:	0x108
BYTE			LCDD6_DriveMode_0_ADDR;
#pragma	ioport	LCDD6_DriveMode_1_ADDR:	0x109
BYTE			LCDD6_DriveMode_1_ADDR;
#pragma	ioport	LCDD6_DriveMode_2_ADDR:	0xb
BYTE			LCDD6_DriveMode_2_ADDR;
#pragma	ioport	LCDD6_GlobalSelect_ADDR:	0xa
BYTE			LCDD6_GlobalSelect_ADDR;
#pragma	ioport	LCDD6_IntCtrl_0_ADDR:	0x10a
BYTE			LCDD6_IntCtrl_0_ADDR;
#pragma	ioport	LCDD6_IntCtrl_1_ADDR:	0x10b
BYTE			LCDD6_IntCtrl_1_ADDR;
#pragma	ioport	LCDD6_IntEn_ADDR:	0x9
BYTE			LCDD6_IntEn_ADDR;
#define LCDD6_MASK 0x4
// LCDD6 Shadow defines
//   LCDD6_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define LCDD6_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
//   LCDD6_DriveMode_0Shadow define
extern BYTE Port_2_DriveMode_0_SHADE;
#define LCDD6_DriveMode_0Shadow (*(unsigned char*)&Port_2_DriveMode_0_SHADE)
//   LCDD6_DriveMode_1Shadow define
extern BYTE Port_2_DriveMode_1_SHADE;
#define LCDD6_DriveMode_1Shadow (*(unsigned char*)&Port_2_DriveMode_1_SHADE)
// LCDD7 address and mask defines
#pragma	ioport	LCDD7_Data_ADDR:	0x8
BYTE			LCDD7_Data_ADDR;
#pragma	ioport	LCDD7_DriveMode_0_ADDR:	0x108
BYTE			LCDD7_DriveMode_0_ADDR;
#pragma	ioport	LCDD7_DriveMode_1_ADDR:	0x109
BYTE			LCDD7_DriveMode_1_ADDR;
#pragma	ioport	LCDD7_DriveMode_2_ADDR:	0xb
BYTE			LCDD7_DriveMode_2_ADDR;
#pragma	ioport	LCDD7_GlobalSelect_ADDR:	0xa
BYTE			LCDD7_GlobalSelect_ADDR;
#pragma	ioport	LCDD7_IntCtrl_0_ADDR:	0x10a
BYTE			LCDD7_IntCtrl_0_ADDR;
#pragma	ioport	LCDD7_IntCtrl_1_ADDR:	0x10b
BYTE			LCDD7_IntCtrl_1_ADDR;
#pragma	ioport	LCDD7_IntEn_ADDR:	0x9
BYTE			LCDD7_IntEn_ADDR;
#define LCDD7_MASK 0x8
// LCDD7 Shadow defines
//   LCDD7_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define LCDD7_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
//   LCDD7_DriveMode_0Shadow define
extern BYTE Port_2_DriveMode_0_SHADE;
#define LCDD7_DriveMode_0Shadow (*(unsigned char*)&Port_2_DriveMode_0_SHADE)
//   LCDD7_DriveMode_1Shadow define
extern BYTE Port_2_DriveMode_1_SHADE;
#define LCDD7_DriveMode_1Shadow (*(unsigned char*)&Port_2_DriveMode_1_SHADE)
// LCDE address and mask defines
#pragma	ioport	LCDE_Data_ADDR:	0x8
BYTE			LCDE_Data_ADDR;
#pragma	ioport	LCDE_DriveMode_0_ADDR:	0x108
BYTE			LCDE_DriveMode_0_ADDR;
#pragma	ioport	LCDE_DriveMode_1_ADDR:	0x109
BYTE			LCDE_DriveMode_1_ADDR;
#pragma	ioport	LCDE_DriveMode_2_ADDR:	0xb
BYTE			LCDE_DriveMode_2_ADDR;
#pragma	ioport	LCDE_GlobalSelect_ADDR:	0xa
BYTE			LCDE_GlobalSelect_ADDR;
#pragma	ioport	LCDE_IntCtrl_0_ADDR:	0x10a
BYTE			LCDE_IntCtrl_0_ADDR;
#pragma	ioport	LCDE_IntCtrl_1_ADDR:	0x10b
BYTE			LCDE_IntCtrl_1_ADDR;
#pragma	ioport	LCDE_IntEn_ADDR:	0x9
BYTE			LCDE_IntEn_ADDR;
#define LCDE_MASK 0x10
// LCDE Shadow defines
//   LCDE_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define LCDE_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
//   LCDE_DriveMode_0Shadow define
extern BYTE Port_2_DriveMode_0_SHADE;
#define LCDE_DriveMode_0Shadow (*(unsigned char*)&Port_2_DriveMode_0_SHADE)
//   LCDE_DriveMode_1Shadow define
extern BYTE Port_2_DriveMode_1_SHADE;
#define LCDE_DriveMode_1Shadow (*(unsigned char*)&Port_2_DriveMode_1_SHADE)
// LCDRS address and mask defines
#pragma	ioport	LCDRS_Data_ADDR:	0x8
BYTE			LCDRS_Data_ADDR;
#pragma	ioport	LCDRS_DriveMode_0_ADDR:	0x108
BYTE			LCDRS_DriveMode_0_ADDR;
#pragma	ioport	LCDRS_DriveMode_1_ADDR:	0x109
BYTE			LCDRS_DriveMode_1_ADDR;
#pragma	ioport	LCDRS_DriveMode_2_ADDR:	0xb
BYTE			LCDRS_DriveMode_2_ADDR;
#pragma	ioport	LCDRS_GlobalSelect_ADDR:	0xa
BYTE			LCDRS_GlobalSelect_ADDR;
#pragma	ioport	LCDRS_IntCtrl_0_ADDR:	0x10a
BYTE			LCDRS_IntCtrl_0_ADDR;
#pragma	ioport	LCDRS_IntCtrl_1_ADDR:	0x10b
BYTE			LCDRS_IntCtrl_1_ADDR;
#pragma	ioport	LCDRS_IntEn_ADDR:	0x9
BYTE			LCDRS_IntEn_ADDR;
#define LCDRS_MASK 0x20
// LCDRS Shadow defines
//   LCDRS_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define LCDRS_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
//   LCDRS_DriveMode_0Shadow define
extern BYTE Port_2_DriveMode_0_SHADE;
#define LCDRS_DriveMode_0Shadow (*(unsigned char*)&Port_2_DriveMode_0_SHADE)
//   LCDRS_DriveMode_1Shadow define
extern BYTE Port_2_DriveMode_1_SHADE;
#define LCDRS_DriveMode_1Shadow (*(unsigned char*)&Port_2_DriveMode_1_SHADE)
// LCDRW address and mask defines
#pragma	ioport	LCDRW_Data_ADDR:	0x8
BYTE			LCDRW_Data_ADDR;
#pragma	ioport	LCDRW_DriveMode_0_ADDR:	0x108
BYTE			LCDRW_DriveMode_0_ADDR;
#pragma	ioport	LCDRW_DriveMode_1_ADDR:	0x109
BYTE			LCDRW_DriveMode_1_ADDR;
#pragma	ioport	LCDRW_DriveMode_2_ADDR:	0xb
BYTE			LCDRW_DriveMode_2_ADDR;
#pragma	ioport	LCDRW_GlobalSelect_ADDR:	0xa
BYTE			LCDRW_GlobalSelect_ADDR;
#pragma	ioport	LCDRW_IntCtrl_0_ADDR:	0x10a
BYTE			LCDRW_IntCtrl_0_ADDR;
#pragma	ioport	LCDRW_IntCtrl_1_ADDR:	0x10b
BYTE			LCDRW_IntCtrl_1_ADDR;
#pragma	ioport	LCDRW_IntEn_ADDR:	0x9
BYTE			LCDRW_IntEn_ADDR;
#define LCDRW_MASK 0x40
// LCDRW Shadow defines
//   LCDRW_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define LCDRW_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
//   LCDRW_DriveMode_0Shadow define
extern BYTE Port_2_DriveMode_0_SHADE;
#define LCDRW_DriveMode_0Shadow (*(unsigned char*)&Port_2_DriveMode_0_SHADE)
//   LCDRW_DriveMode_1Shadow define
extern BYTE Port_2_DriveMode_1_SHADE;
#define LCDRW_DriveMode_1Shadow (*(unsigned char*)&Port_2_DriveMode_1_SHADE)
