;  Generated by PSoC Designer 5.4.2946
;
; =============================================================================
; FILENAME: PSoCConfigTBL.asm
;  
; Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
;  
; NOTES:
; Do not modify this file. It is generated by PSoC Designer each time the
; generate application function is run. The values of the parameters in this
; file can be modified by changing the values of the global parameters in the
; device editor.
;  
; =============================================================================
 
include "m8c.inc"
;  Personalization tables 
export LoadConfigTBL_frequencyproject
AREA psoc_config(rom, rel)
LoadConfigTBL_frequencyproject:
	M8C_SetBank0
;  Global Register values Bank 0
	mov	reg[60h], 2bh		; AnalogColumnInputSelect register (AMX_IN)
	mov	reg[66h], 00h		; AnalogComparatorControl1 register (CMP_CR1)
	mov	reg[63h], 07h		; AnalogReferenceControl register (ARF_CR)
	mov	reg[65h], 00h		; AnalogSyncControl register (ASY_CR)
	mov	reg[e6h], 02h		; DecimatorControl_0 register (DEC_CR0)
	mov	reg[e7h], 00h		; DecimatorControl_1 register (DEC_CR1)
	mov	reg[d6h], 00h		; I2CConfig register (I2C_CFG)
	mov	reg[b0h], 00h		; Row_0_InputMux register (RDI0RI)
	mov	reg[b1h], 00h		; Row_0_InputSync register (RDI0SYN)
	mov	reg[b2h], 00h		; Row_0_LogicInputAMux register (RDI0IS)
	mov	reg[b3h], 33h		; Row_0_LogicSelect_0 register (RDI0LT0)
	mov	reg[b4h], 33h		; Row_0_LogicSelect_1 register (RDI0LT1)
	mov	reg[b5h], 00h		; Row_0_OutputDrive_0 register (RDI0SRO0)
	mov	reg[b6h], 00h		; Row_0_OutputDrive_1 register (RDI0SRO1)
	mov	reg[b8h], 55h		; Row_1_InputMux register (RDI1RI)
	mov	reg[b9h], 00h		; Row_1_InputSync register (RDI1SYN)
	mov	reg[bah], 10h		; Row_1_LogicInputAMux register (RDI1IS)
	mov	reg[bbh], 33h		; Row_1_LogicSelect_0 register (RDI1LT0)
	mov	reg[bch], 33h		; Row_1_LogicSelect_1 register (RDI1LT1)
	mov	reg[bdh], 20h		; Row_1_OutputDrive_0 register (RDI1SRO0)
	mov	reg[beh], 00h		; Row_1_OutputDrive_1 register (RDI1SRO1)
	mov	reg[c0h], 00h		; Row_2_InputMux register (RDI2RI)
	mov	reg[c1h], 00h		; Row_2_InputSync register (RDI2SYN)
	mov	reg[c2h], 20h		; Row_2_LogicInputAMux register (RDI2IS)
	mov	reg[c3h], 33h		; Row_2_LogicSelect_0 register (RDI2LT0)
	mov	reg[c4h], 33h		; Row_2_LogicSelect_1 register (RDI3LT1)
	mov	reg[c5h], 00h		; Row_2_OutputDrive_0 register (RDI2SRO0)
	mov	reg[c6h], 00h		; Row_2_OutputDrive_1 register (RDI2SRO1)
	mov	reg[c8h], 55h		; Row_3_InputMux register (RDI3RI)
	mov	reg[c9h], 00h		; Row_3_InputSync register (RDI3SYN)
	mov	reg[cah], 30h		; Row_3_LogicInputAMux register (RDI3IS)
	mov	reg[cbh], 33h		; Row_3_LogicSelect_0 register (RDI3LT0)
	mov	reg[cch], 33h		; Row_3_LogicSelect_1 register (RDI3LT1)
	mov	reg[cdh], 00h		; Row_3_OutputDrive_0 register (RDI3SRO0)
	mov	reg[ceh], 00h		; Row_3_OutputDrive_1 register (RDI3SRO1)
	mov	reg[6ch], 00h		; TMP_DR0 register (TMP_DR0)
	mov	reg[6dh], 00h		; TMP_DR1 register (TMP_DR1)
	mov	reg[6eh], 00h		; TMP_DR2 register (TMP_DR2)
	mov	reg[6fh], 00h		; TMP_DR3 register (TMP_DR3)
;  Instance name Comparator, User Module CMPPRG
;       Instance name Comparator, Block Name COMP(ACB00)
	mov	reg[71h], 7ah		;Comparator_COMP_CR0(ACB00CR0)
	mov	reg[72h], 61h		;Comparator_COMP_CR1(ACB00CR1)
	mov	reg[73h], 40h		;Comparator_COMP_CR2(ACB00CR2)
	mov	reg[70h], 00h		;Comparator_COMP_CR3(ACB00CR3)
;  Instance name LCD, User Module LCD
;  Instance name SampleFreq, User Module Counter24
;       Instance name SampleFreq, Block Name CNTR24_ISB(DBB11)
	mov	reg[37h], 00h		;SampleFreq_CONTROL_ISB_REG(DBB11CR0)
	mov	reg[35h], 25h		;SampleFreq_PERIOD_ISB_REG(DBB11DR1)
	mov	reg[36h], 12h		;SampleFreq_COMPARE_ISB_REG(DBB11DR2)
;       Instance name SampleFreq, Block Name CNTR24_LSB(DBB10)
	mov	reg[33h], 00h		;SampleFreq_CONTROL_LSB_REG(DBB10CR0)
	mov	reg[31h], f7h		;SampleFreq_PERIOD_LSB_REG(DBB10DR1)
	mov	reg[32h], fch		;SampleFreq_COMPARE_LSB_REG(DBB10DR2)
;       Instance name SampleFreq, Block Name CNTR24_MSB(DCB12)
	mov	reg[3bh], 00h		;SampleFreq_CONTROL_MSB_REG(DCB12CR0)
	mov	reg[39h], 00h		;SampleFreq_PERIOD_MSB_REG(DCB12DR1)
	mov	reg[3ah], 00h		;SampleFreq_COMPARE_MSB_REG(DCB12DR2)
;  Instance name TickTimer, User Module Timer16
;       Instance name TickTimer, Block Name TIMER16_LSB(DBB00)
	mov	reg[23h], 00h		;TickTimer_CONTROL_LSB_REG(DBB00CR0)
	mov	reg[21h], ffh		;TickTimer_PERIOD_LSB_REG(DBB00DR1)
	mov	reg[22h], 00h		;TickTimer_COMPARE_LSB_REG(DBB00DR2)
;       Instance name TickTimer, Block Name TIMER16_MSB(DBB01)
	mov	reg[27h], 04h		;TickTimer_CONTROL_MSB_REG(DBB01CR0)
	mov	reg[25h], ffh		;TickTimer_PERIOD_MSB_REG(DBB01DR1)
	mov	reg[26h], 00h		;TickTimer_COMPARE_MSB_REG(DBB01DR2)
	M8C_SetBank1
;  Global Register values Bank 1
	mov	reg[61h], 00h		; AnalogClockSelect1 register (CLK_CR1)
	mov	reg[69h], 00h		; AnalogClockSelect2 register (CLK_CR2)
	mov	reg[60h], 00h		; AnalogColumnClockSelect register (CLK_CR0)
	mov	reg[62h], 00h		; AnalogIOControl_0 register (ABF_CR0)
	mov	reg[67h], 33h		; AnalogLUTControl0 register (ALT_CR0)
	mov	reg[68h], 33h		; AnalogLUTControl1 register (ALT_CR1)
	mov	reg[63h], 00h		; AnalogModulatorControl_0 register (AMD_CR0)
	mov	reg[66h], 00h		; AnalogModulatorControl_1 register (AMD_CR1)
	mov	reg[d1h], 00h		; GlobalDigitalInterconnect_Drive_Even_Input register (GDI_E_IN)
	mov	reg[d3h], 00h		; GlobalDigitalInterconnect_Drive_Even_Output register (GDI_E_OU)
	mov	reg[d0h], 00h		; GlobalDigitalInterconnect_Drive_Odd_Input register (GDI_O_IN)
	mov	reg[d2h], 00h		; GlobalDigitalInterconnect_Drive_Odd_Output register (GDI_O_OU)
	mov	reg[e1h], 1fh		; OscillatorControl_1 register (OSC_CR1)
	mov	reg[e2h], 00h		; OscillatorControl_2 register (OSC_CR2)
	mov	reg[dfh], b7h		; OscillatorControl_3 register (OSC_CR3)
	mov	reg[deh], 01h		; OscillatorControl_4 register (OSC_CR4)
	mov	reg[ddh], 00h		; OscillatorGlobalBusEnableControl register (OSC_GO_EN)
	mov	reg[e7h], 00h		; Type2Decimator_Control register (DEC_CR2)
;  Instance name Comparator, User Module CMPPRG
;       Instance name Comparator, Block Name COMP(ACB00)
;  Instance name LCD, User Module LCD
;  Instance name SampleFreq, User Module Counter24
;       Instance name SampleFreq, Block Name CNTR24_ISB(DBB11)
	mov	reg[34h], 11h		;SampleFreq_FUNC_ISB_REG(DBB11FN)
	mov	reg[35h], 35h		;SampleFreq_INPUT_ISB_REG(DBB11IN)
	mov	reg[36h], 40h		;SampleFreq_OUTPUT_ISB_REG(DBB11OU)
;       Instance name SampleFreq, Block Name CNTR24_LSB(DBB10)
	mov	reg[30h], 11h		;SampleFreq_FUNC_LSB_REG(DBB10FN)
	mov	reg[31h], 15h		;SampleFreq_INPUT_LSB_REG(DBB10IN)
	mov	reg[32h], 40h		;SampleFreq_OUTPUT_LSB_REG(DBB10OU)
;       Instance name SampleFreq, Block Name CNTR24_MSB(DCB12)
	mov	reg[38h], 31h		;SampleFreq_FUNC_MSB_REG(DCB12FN)
	mov	reg[39h], 35h		;SampleFreq_INPUT_MSB_REG(DCB12IN)
	mov	reg[3ah], 45h		;SampleFreq_OUTPUT_MSB_REG(DCB12OU)
;  Instance name TickTimer, User Module Timer16
;       Instance name TickTimer, Block Name TIMER16_LSB(DBB00)
	mov	reg[20h], 10h		;TickTimer_FUNC_LSB_REG(DBB00FN)
	mov	reg[21h], 41h		;TickTimer_INPUT_LSB_REG(DBB00IN)
	mov	reg[22h], 40h		;TickTimer_OUTPUT_LSB_REG(DBB00OU)
;       Instance name TickTimer, Block Name TIMER16_MSB(DBB01)
	mov	reg[24h], 30h		;TickTimer_FUNC_MSB_REG(DBB01FN)
	mov	reg[25h], 31h		;TickTimer_INPUT_MSB_REG(DBB01IN)
	mov	reg[26h], 40h		;TickTimer_OUTPUT_MSB_REG(DBB01OU)
	M8C_SetBank0
;  Ordered Global Register values
	M8C_SetBank0
	mov	reg[00h], 80h		; Port_0_Data register (PRT0DR)
	M8C_SetBank1
	mov	reg[00h], b0h		; Port_0_DriveMode_0 register (PRT0DM0)
	mov	reg[01h], cfh		; Port_0_DriveMode_1 register (PRT0DM1)
	M8C_SetBank0
	mov	reg[03h], 4fh		; Port_0_DriveMode_2 register (PRT0DM2)
	mov	reg[02h], 20h		; Port_0_GlobalSelect register (PRT0GS)
	M8C_SetBank1
	mov	reg[02h], 00h		; Port_0_IntCtrl_0 register (PRT0IC0)
	mov	reg[03h], 00h		; Port_0_IntCtrl_1 register (PRT0IC1)
	M8C_SetBank0
	mov	reg[01h], 00h		; Port_0_IntEn register (PRT0IE)
	mov	reg[04h], 00h		; Port_1_Data register (PRT1DR)
	M8C_SetBank1
	mov	reg[04h], 80h		; Port_1_DriveMode_0 register (PRT1DM0)
	mov	reg[05h], 7fh		; Port_1_DriveMode_1 register (PRT1DM1)
	M8C_SetBank0
	mov	reg[07h], 7ch		; Port_1_DriveMode_2 register (PRT1DM2)
	mov	reg[06h], 00h		; Port_1_GlobalSelect register (PRT1GS)
	M8C_SetBank1
	mov	reg[06h], 00h		; Port_1_IntCtrl_0 register (PRT1IC0)
	mov	reg[07h], 00h		; Port_1_IntCtrl_1 register (PRT1IC1)
	M8C_SetBank0
	mov	reg[05h], 00h		; Port_1_IntEn register (PRT1IE)
	mov	reg[08h], 00h		; Port_2_Data register (PRT2DR)
	M8C_SetBank1
	mov	reg[08h], 7fh		; Port_2_DriveMode_0 register (PRT2DM0)
	mov	reg[09h], 80h		; Port_2_DriveMode_1 register (PRT2DM1)
	M8C_SetBank0
	mov	reg[0bh], 80h		; Port_2_DriveMode_2 register (PRT2DM2)
	mov	reg[0ah], 00h		; Port_2_GlobalSelect register (PRT2GS)
	M8C_SetBank1
	mov	reg[0ah], 00h		; Port_2_IntCtrl_0 register (PRT2IC0)
	mov	reg[0bh], 00h		; Port_2_IntCtrl_1 register (PRT2IC1)
	M8C_SetBank0
	mov	reg[09h], 00h		; Port_2_IntEn register (PRT2IE)
	mov	reg[0ch], 00h		; Port_3_Data register (PRT3DR)
	M8C_SetBank1
	mov	reg[0ch], 00h		; Port_3_DriveMode_0 register (PRT3DM0)
	mov	reg[0dh], 00h		; Port_3_DriveMode_1 register (PRT3DM1)
	M8C_SetBank0
	mov	reg[0fh], 00h		; Port_3_DriveMode_2 register (PRT3DM2)
	mov	reg[0eh], 00h		; Port_3_GlobalSelect register (PRT3GS)
	M8C_SetBank1
	mov	reg[0eh], 00h		; Port_3_IntCtrl_0 register (PRT3IC0)
	mov	reg[0fh], 00h		; Port_3_IntCtrl_1 register (PRT3IC1)
	M8C_SetBank0
	mov	reg[0dh], 00h		; Port_3_IntEn register (PRT3IE)
	mov	reg[10h], 00h		; Port_4_Data register (PRT4DR)
	M8C_SetBank1
	mov	reg[10h], 00h		; Port_4_DriveMode_0 register (PRT4DM0)
	mov	reg[11h], 00h		; Port_4_DriveMode_1 register (PRT4DM1)
	M8C_SetBank0
	mov	reg[13h], 00h		; Port_4_DriveMode_2 register (PRT4DM2)
	mov	reg[12h], 00h		; Port_4_GlobalSelect register (PRT4GS)
	M8C_SetBank1
	mov	reg[12h], 00h		; Port_4_IntCtrl_0 register (PRT4IC0)
	mov	reg[13h], 00h		; Port_4_IntCtrl_1 register (PRT4IC1)
	M8C_SetBank0
	mov	reg[11h], 00h		; Port_4_IntEn register (PRT4IE)
	mov	reg[14h], 00h		; Port_5_Data register (PRT5DR)
	M8C_SetBank1
	mov	reg[14h], 00h		; Port_5_DriveMode_0 register (PRT5DM0)
	mov	reg[15h], 00h		; Port_5_DriveMode_1 register (PRT5DM1)
	M8C_SetBank0
	mov	reg[17h], 00h		; Port_5_DriveMode_2 register (PRT5DM2)
	mov	reg[16h], 00h		; Port_5_GlobalSelect register (PRT5GS)
	M8C_SetBank1
	mov	reg[16h], 00h		; Port_5_IntCtrl_0 register (PRT5IC0)
	mov	reg[17h], 00h		; Port_5_IntCtrl_1 register (PRT5IC1)
	M8C_SetBank0
	mov	reg[15h], 00h		; Port_5_IntEn register (PRT5IE)
	mov	reg[18h], 00h		; Port_6_Data register (PRT6DR)
	M8C_SetBank1
	mov	reg[18h], 00h		; Port_6_DriveMode_0 register (PRT6DM0)
	mov	reg[19h], 00h		; Port_6_DriveMode_1 register (PRT6DM1)
	M8C_SetBank0
	mov	reg[1bh], 00h		; Port_6_DriveMode_2 register (PRT6DM2)
	mov	reg[1ah], 00h		; Port_6_GlobalSelect register (PRT6GS)
	M8C_SetBank1
	mov	reg[1ah], 00h		; Port_6_IntCtrl_0 register (PRT6IC0)
	mov	reg[1bh], 00h		; Port_6_IntCtrl_1 register (PRT6IC1)
	M8C_SetBank0
	mov	reg[19h], 00h		; Port_6_IntEn register (PRT6IE)
	mov	reg[1ch], 00h		; Port_7_Data register (PRT7DR)
	M8C_SetBank1
	mov	reg[1ch], 00h		; Port_7_DriveMode_0 register (PRT7DM0)
	mov	reg[1dh], 00h		; Port_7_DriveMode_1 register (PRT7DM1)
	M8C_SetBank0
	mov	reg[1fh], 00h		; Port_7_DriveMode_2 register (PRT7DM2)
	mov	reg[1eh], 00h		; Port_7_GlobalSelect register (PRT7GS)
	M8C_SetBank1
	mov	reg[1eh], 00h		; Port_7_IntCtrl_0 register (PRT7IC0)
	mov	reg[1fh], 00h		; Port_7_IntCtrl_1 register (PRT7IC1)
	M8C_SetBank0
	mov	reg[1dh], 00h		; Port_7_IntEn register (PRT7IE)
	M8C_SetBank0
	ret


; PSoC Configuration file trailer PsocConfig.asm
