//*****************************************************************************
//*****************************************************************************
//  FILENAME:  Comparator.h
//  Version: 3.3, Updated on 2013/5/19 at 10:42:26
//  Generated by PSoC Designer 5.4.2946
//
//  DESCRIPTION:  CMPPRG User Module C Language interface file.
//-----------------------------------------------------------------------------
//      Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef Comparator_INCLUDE
#define Comparator_INCLUDE

#include <M8C.h>

//-------------------------------------------------
// Defines for Comparator API's.
//-------------------------------------------------
#define Comparator_OFF         0
#define Comparator_LOWPOWER    1
#define Comparator_MEDPOWER    2
#define Comparator_HIGHPOWER   3

#define Comparator_REF1_000   0xf0
#define Comparator_REF0_937   0xe0
#define Comparator_REF0_875   0xd0
#define Comparator_REF0_812   0xc0
#define Comparator_REF0_750   0xb0
#define Comparator_REF0_688   0xa0
#define Comparator_REF0_625   0x90
#define Comparator_REF0_562   0x80
#define Comparator_REF0_500   0x70
#define Comparator_REF0_437   0x60
#define Comparator_REF0_375   0x50
#define Comparator_REF0_312   0x40
#define Comparator_REF0_250   0x30
#define Comparator_REF0_188   0x20
#define Comparator_REF0_125   0x10
#define Comparator_REF0_062   0x00
#define Comparator_REF0_042   0x14
#define Comparator_REF0_021   0x04


#pragma fastcall16 Comparator_Start             // Proxy class 2
#pragma fastcall16 Comparator_SetPower          // Proxy class 2
#pragma fastcall16 Comparator_SetRef            // Proxy class 2
#pragma fastcall16 Comparator_Stop              // Proxy class 1

//-------------------------------------------------
// Prototypes of the Comparator API.
//-------------------------------------------------
extern void Comparator_Start(BYTE bPowerSetting);
extern void Comparator_SetPower(BYTE bPowerSetting);
extern void Comparator_SetRef(BYTE bRefValue);
extern void Comparator_Stop(void);

//-------------------------------------------------
// Hardware Register Definitions
//-------------------------------------------------
#pragma ioport  Comparator_COMP_CR0:    0x071
BYTE            Comparator_COMP_CR0;
#pragma ioport  Comparator_COMP_CR1:    0x072
BYTE            Comparator_COMP_CR1;
#pragma ioport  Comparator_COMP_CR2:    0x073
BYTE            Comparator_COMP_CR2;
#pragma ioport  Comparator_COMP_CR3:    0x070
BYTE            Comparator_COMP_CR3;

#endif
// end of file Comparator.h
