//*****************************************************************************
//*****************************************************************************
//  FILENAME: SampleFreq.h
//   Version: 2.5, Updated on 2013/5/19 at 10:42:31
//  Generated by PSoC Designer 5.4.2946
//
//  DESCRIPTION: Counter24 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef SampleFreq_INCLUDE
#define SampleFreq_INCLUDE

#include <m8c.h>

#pragma fastcall16 SampleFreq_EnableInt
#pragma fastcall16 SampleFreq_DisableInt
#pragma fastcall16 SampleFreq_Start
#pragma fastcall16 SampleFreq_Stop
#pragma fastcall16 SampleFreq_ReadCounter              // Read  DR0
#pragma fastcall16 SampleFreq_WritePeriod              // Write DR1
#pragma fastcall16 SampleFreq_ReadCompareValue         // Read  DR2
#pragma fastcall16 SampleFreq_WriteCompareValue        // Write DR2


//-------------------------------------------------
// Prototypes of the SampleFreq API.
//-------------------------------------------------
                                                                           
extern void SampleFreq_EnableInt(void);                           // Proxy Class 1
extern void SampleFreq_DisableInt(void);                          // Proxy Class 1
extern void SampleFreq_Start(void);                               // Proxy Class 1
extern void SampleFreq_Stop(void);                                // Proxy Class 1
extern void SampleFreq_ReadCounter(DWORD * pdwCount);             // Proxy Class 3
extern void SampleFreq_WritePeriod(DWORD dwPeriod);               // Proxy Class 2
extern void SampleFreq_ReadCompareValue(DWORD * pdwCompareValue); // Proxy Class 3
extern void SampleFreq_WriteCompareValue(DWORD dwCompareValue);   // Proxy Class 2


//--------------------------------------------------
// Constants for SampleFreq API's.
//--------------------------------------------------

#define SampleFreq_CONTROL_REG_START_BIT       ( 0x01 )
#define SampleFreq_INT_REG_ADDR                ( 0x0e1 )
#define SampleFreq_INT_MASK                    ( 0x40 )


//--------------------------------------------------
// Constants for SampleFreq user defined values
//--------------------------------------------------

#define SampleFreq_PERIOD                      ( 0x25f7 )
#define SampleFreq_COMPARE_VALUE               ( 0x12fc )


//-------------------------------------------------
// Register Addresses for SampleFreq
//-------------------------------------------------

#pragma ioport  SampleFreq_COUNTER_LSB_REG: 0x030          //Count register LSB
BYTE            SampleFreq_COUNTER_LSB_REG;
#pragma ioport  SampleFreq_COUNTER_ISB_REG: 0x034          //Count register ISB
BYTE            SampleFreq_COUNTER_ISB_REG;
#pragma ioport  SampleFreq_COUNTER_MSB_REG: 0x038          //Count register MSB
BYTE            SampleFreq_COUNTER_MSB_REG;
#pragma ioport  SampleFreq_PERIOD_LSB_REG:  0x031          //Period register LSB
BYTE            SampleFreq_PERIOD_LSB_REG;
#pragma ioport  SampleFreq_PERIOD_ISB_REG:  0x035          //Period register ISB
BYTE            SampleFreq_PERIOD_ISB_REG;
#pragma ioport  SampleFreq_PERIOD_MSB_REG:  0x039          //Period register MSB
BYTE            SampleFreq_PERIOD_MSB_REG;
#pragma ioport  SampleFreq_COMPARE_LSB_REG: 0x032          //Compare register LSB
BYTE            SampleFreq_COMPARE_LSB_REG;
#pragma ioport  SampleFreq_COMPARE_ISB_REG: 0x036          //Compare register ISB
BYTE            SampleFreq_COMPARE_ISB_REG;
#pragma ioport  SampleFreq_COMPARE_MSB_REG: 0x03a          //Compare register MSB
BYTE            SampleFreq_COMPARE_MSB_REG;
#pragma ioport  SampleFreq_CONTROL_LSB_REG: 0x033          //Control register LSB
BYTE            SampleFreq_CONTROL_LSB_REG;
#pragma ioport  SampleFreq_CONTROL_ISB_REG: 0x037          //Control register ISB
BYTE            SampleFreq_CONTROL_ISB_REG;
#pragma ioport  SampleFreq_CONTROL_MSB_REG: 0x03b          //Control register MSB
BYTE            SampleFreq_CONTROL_MSB_REG;
#pragma ioport  SampleFreq_FUNC_LSB_REG:    0x130          //Function register LSB
BYTE            SampleFreq_FUNC_LSB_REG;
#pragma ioport  SampleFreq_FUNC_ISB_REG:    0x134          //Function register ISB
BYTE            SampleFreq_FUNC_ISB_REG;
#pragma ioport  SampleFreq_FUNC_MSB_REG:    0x138          //Function register MSB
BYTE            SampleFreq_FUNC_MSB_REG;
#pragma ioport  SampleFreq_INPUT_LSB_REG:   0x131          //Input register LSB
BYTE            SampleFreq_INPUT_LSB_REG;
#pragma ioport  SampleFreq_INPUT_ISB_REG:   0x135          //Input register ISB
BYTE            SampleFreq_INPUT_ISB_REG;
#pragma ioport  SampleFreq_INPUT_MSB_REG:   0x139          //Input register MSB
BYTE            SampleFreq_INPUT_MSB_REG;
#pragma ioport  SampleFreq_OUTPUT_LSB_REG:  0x132          //Output register LSB
BYTE            SampleFreq_OUTPUT_LSB_REG;
#pragma ioport  SampleFreq_OUTPUT_ISB_REG:  0x136          //Output register ISB
BYTE            SampleFreq_OUTPUT_ISB_REG;
#pragma ioport  SampleFreq_OUTPUT_MSB_REG:  0x13a          //Output register MSB
BYTE            SampleFreq_OUTPUT_MSB_REG;
#pragma ioport  SampleFreq_INT_REG:       0x0e1            //Interrupt Mask Register
BYTE            SampleFreq_INT_REG;


//-------------------------------------------------
// SampleFreq Macro 'Functions'
//-------------------------------------------------

#define SampleFreq_Start_M \
   ( SampleFreq_CONTROL_LSB_REG |=  SampleFreq_CONTROL_REG_START_BIT )

#define SampleFreq_Stop_M  \
   ( SampleFreq_CONTROL_LSB_REG &= ~SampleFreq_CONTROL_REG_START_BIT )

#define SampleFreq_EnableInt_M   \
   M8C_EnableIntMask(  SampleFreq_INT_REG, SampleFreq_INT_MASK )

#define SampleFreq_DisableInt_M  \
   M8C_DisableIntMask( SampleFreq_INT_REG, SampleFreq_INT_MASK )

#endif
// end of file SampleFreq.h
