;;*****************************************************************************
;;*****************************************************************************
;;  FILENAME: TickTimerINT.asm
;;   Version: 2.6, Updated on 2013/5/19 at 10:44:39
;;  Generated by PSoC Designer 5.4.2946
;;
;;  DESCRIPTION: Timer16 Interrupt Service Routine
;;-----------------------------------------------------------------------------
;;  Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
;;*****************************************************************************
;;*****************************************************************************

include "m8c.inc"
include "memory.inc"
include "TickTimer.inc"


;-----------------------------------------------
;  Global Symbols
;-----------------------------------------------
export  _TickTimer_ISR


AREA InterruptRAM (RAM,REL,CON)

;@PSoC_UserCode_INIT@ (Do not change this line.)
;---------------------------------------------------
; Insert your custom declarations below this banner
;---------------------------------------------------
export  _cOverFlow
export _wTickCount
export _wFirstValue
export _wLastValue
export _cSaveOverFlow
export _wSaveTickNum
export _wSaveCountNum
export _bDataAvailable:
;------------------------
; Includes
;------------------------

	
;------------------------
;  Constant Definitions
;------------------------


;------------------------
; Variable Allocation
;------------------------
_cOverFlow:      BLK  1
_wTickCount:     BLK  2
_wFirstValue:    BLK  2
_wLastValue:     BLK  2
_cSaveOverFlow:  BLK  1
_wSaveTickNum:   BLK  2
_wSaveCountNum:  BLK  2
_bDataAvailable: BLK  1

;---------------------------------------------------
; Insert your custom declarations above this banner
;---------------------------------------------------
;@PSoC_UserCode_END@ (Do not change this line.)


AREA UserModules (ROM, REL)

;-----------------------------------------------------------------------------
;  FUNCTION NAME: _TickTimer_ISR
;
;  DESCRIPTION: Unless modified, this implements only a null handler stub.
;
;-----------------------------------------------------------------------------
;

_TickTimer_ISR:

   ;@PSoC_UserCode_BODY@ (Do not change this line.)
   ;---------------------------------------------------
   ; Insert your custom code below this banner
   ;---------------------------------------------------
    push A
    mov  [_wSaveCountNum + 1],[_wFirstValue + 1]
    mov  [_wSaveCountNum + 0],[_wFirstValue + 0]  
    mov  A,[_wLastValue  + 1]
    sub  [_wSaveCountNum + 1],A
    mov  A,[_wLastValue  + 0]
    sbb  [_wSaveCountNum + 0],A
    
    mov  [_cSaveOverFlow]    ,[_cOverFlow]
    mov  [_wSaveTickNum + 0 ],[_wTickCount + 0]
    mov  [_wSaveTickNum + 1 ],[_wTickCount + 1]
    
    mov  A,ffh
    mov  [_cOverFlow],A
    mov  [_wTickCount +  0],A
    mov  [_wTickCount +  1],A
    mov  [_bDataAvailable],A
    pop  A
   ;---------------------------------------------------
   ; Insert your custom code above this banner
   ;---------------------------------------------------
   ;@PSoC_UserCode_END@ (Do not change this line.)

   reti


; end of file TickTimerINT.asm
