//*****************************************************************************
//*****************************************************************************
//  FILENAME: CRC16.h
//   Version: 3.2, Updated on 2014/7/14 at 8:9:8
//  Generated by PSoC Designer 5.4.2946
//
//  DESCRIPTION: CRC16 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2014. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef CRC16_INCLUDE
#define CRC16_INCLUDE

#include <m8c.h>

#pragma fastcall16  CRC16_Start
#pragma fastcall16  CRC16_Stop
#pragma fastcall16  CRC16_WriteSeed
#pragma fastcall16  CRC16_WritePolynomial
#pragma fastcall16  CRC16_wReadCRC

//-------------------------------------------------
// Prototypes of the CRC16 API.
//-------------------------------------------------
extern void  CRC16_Start(void);                                 // Proxy Class 1
extern void  CRC16_Stop(void);                                  // Proxy Class 1
extern void  CRC16_WriteSeed(WORD wSeed);                       // Proxy Class 1
extern void  CRC16_WritePolynomial(WORD wPolynomial);           // Proxy Class 1
extern WORD  CRC16_wReadCRC(void);                              // Proxy Class 1



//-------------------------------------------------
// Do not use! For backwards compatibility only.
#pragma fastcall16 wCRC16_ReadCRC
extern WORD wCRC16_ReadCRC(void);
//-------------------------------------------------

//-------------------------------------------------
// Constants for CRC16 API's.
//-------------------------------------------------

//CCITT Polynomial and Seed
#define  CRC_CCITT_POLYNOMIAL    0x8810
#define  CRC_CCITT_SEED          0xFFFF

//CRC-16 Polynomial and Seed
#define  CRC_16_POLYNOMIAL       0xC002
#define  CRC_16_SEED             0x0000

//-------------------------------------------------
// Register Addresses for CRC16
//-------------------------------------------------
#pragma ioport  CRC16_CONTROL_LSB_REG:  0x023
BYTE            CRC16_CONTROL_LSB_REG;                      // Control register LSB
#pragma ioport  CRC16_CONTROL_MSB_REG:  0x027
BYTE            CRC16_CONTROL_MSB_REG;                      // Control register MSB
#pragma ioport  CRC16_SHIFT_LSB_REG:    0x020
BYTE            CRC16_SHIFT_LSB_REG;                        // Shift register LSB
#pragma ioport  CRC16_SHIFT_MSB_REG:    0x024
BYTE            CRC16_SHIFT_MSB_REG;                        // Shift register MSB
#pragma ioport  CRC16_POLY_LSB_REG: 0x021
BYTE            CRC16_POLY_LSB_REG;                         // Polynomial register LSB
#pragma ioport  CRC16_POLY_MSB_REG: 0x025
BYTE            CRC16_POLY_MSB_REG;                         // Polynomial register MSB
#pragma ioport  CRC16_SEED_LSB_REG: 0x022
BYTE            CRC16_SEED_LSB_REG;                         // Seed register LSB
#pragma ioport  CRC16_SEED_MSB_REG: 0x026
BYTE            CRC16_SEED_MSB_REG;                         // Seed register MSB
#pragma ioport  CRC16_FUNC_LSB_REG: 0x120
BYTE            CRC16_FUNC_LSB_REG;                         // Function register LSB
#pragma ioport  CRC16_FUNC_MSB_REG: 0x124
BYTE            CRC16_FUNC_MSB_REG;                         // Function register MSB
#pragma ioport  CRC16_INPUT_LSB_REG:    0x121
BYTE            CRC16_INPUT_LSB_REG;                        // Input register LSB
#pragma ioport  CRC16_INPUT_MSB_REG:    0x125
BYTE            CRC16_INPUT_MSB_REG;                        // Input register MSB
#pragma ioport  CRC16_OUTPUT_LSB_REG:   0x122
BYTE            CRC16_OUTPUT_LSB_REG;                       // Output register LSB
#pragma ioport  CRC16_OUTPUT_MSB_REG:   0x126
BYTE            CRC16_OUTPUT_MSB_REG;                       // Output register MSB

#endif
// end of file CRC16.h
