;  Generated by PSoC Designer 5.4.3191
;
;;*****************************************************************************
;;*****************************************************************************
;;  FILENAME: PSoCGPIOINT.asm
;;   Version: 2.0.0.20, Updated on 2003/07/17 at 12:10:35
;;  @PSOC_VERSION
;;
;;  DESCRIPTION: PSoC GPIO Interrupt Service Routine
;;-----------------------------------------------------------------------------
;;  Copyright (c) Cypress Semiconductor 2015. All Rights Reserved.
;;*****************************************************************************
;;*****************************************************************************

include "m8c.inc"
include "PSoCGPIOINT.inc"

;-----------------------------------------------
;  Global Symbols
;-----------------------------------------------
export   PSoC_GPIO_ISR


;-----------------------------------------------
;  Constant Definitions
;-----------------------------------------------


;-----------------------------------------------
; Variable Allocation
;-----------------------------------------------
	

;@PSoC_UserCode_INIT@ (Do not change this line.)
;---------------------------------------------------
; Insert your custom declarations below this banner
;---------------------------------------------------

;---------------------------------------------------
; Insert your custom declarations above this banner
;---------------------------------------------------
;@PSoC_UserCode_END@ (Do not change this line.)


;-----------------------------------------------------------------------------
;  FUNCTION NAME: PSoC_GPIO_ISR
;
;  DESCRIPTION: Unless modified, this implements only a null handler stub.
;
;-----------------------------------------------------------------------------
;
PSoC_GPIO_ISR:


   ;@PSoC_UserCode_BODY@ (Do not change this line.)
   ;---------------------------------------------------
   ; Insert your custom code below this banner
   ;---------------------------------------------------
	push A
	push X


    ;toggle LEDs
;	mov A, reg[PRT1DR]
;	xor A, FFh 										;don't toggle LED 0
;	mov reg[PRT1DR], A
	
	;present numbr of interrupt on LCD
	inc [250]
	mov A, 00h
	mov X, 00h
	call LCD_Position
	mov A, [250]
	call LCD_PrHexByte
	
;	;ideally present time on LCD
;	lcall Timer16_sec_wReadTimer
;	mov [251], A						;hold on to A value
;	mov [252], X
;
;	;lsb
;	mov A, 01h							;put position before then just output A?
;	mov X, 02h
;	call LCD_Position
;	mov A, [251]
;	call LCD_PrHexByte
;	;msb
;	mov A, 01h							;put position before then just output A?
;	mov X, 00h
;	call LCD_Position
;	mov A, [252]
;	call LCD_PrHexByte
	
	
	pop X
	pop A
   ;---------------------------------------------------
   ; Insert your custom code above this banner
   ;---------------------------------------------------
   ;@PSoC_UserCode_END@ (Do not change this line.)

   reti


; end of file PSoCGPIOINT.asm
